config/routes.rb
MusicApp::Application.routes.draw do
  resources :users do
    collection do
      get 'activate'
    end
  end
  resource :sessions

  resources :bands do
    resources :albums, :only => [:index, :new, :create, :edit, :update]
  end
  resources :albums, :only => [:show, :destroy] do
    resources :tracks, :only => [:index, :new, :create, :edit, :update]
  end
  resources :tracks, :only => [:show, :destroy]
  resources :notes, :only => [:create, :destroy]

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :album_name, :band_id, :album_type

  validates :album_name, :band_id, :album_type, :presence => true
  validates :album_type, :inclusion => { :in => %w( live studio ) }

  belongs_to(
    :band,
    class_name: "Band",
    foreign_key: :band_id,
    primary_key: :id
  )

  has_many(
    :tracks,
    class_name: "Track",
    foreign_key: :album_id,
    primary_key: :id,
    dependent: :destroy
  )
end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :band_name

  validates :band_name, :presence => true

  has_many(
    :albums,
    class_name: "Album",
    foreign_key: :band_id,
    primary_key: :id,
    dependent: :destroy
  )
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :user_id, :track_id, :contents

  validates :user_id, :track_id, :contents, :presence => true

  belongs_to(
    :author,
    :class_name => "User",
    :foreign_key => :user_id,
    :primary_key => :id
  )

  belongs_to(
    :track,
    :class_name => "Track",
    :foreign_key => :track_id,
    :primary_key => :id
  )
end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :album_id, :lyrics, :track_name, :track_type

  validates :album_id, :track_name, :track_type, :presence => true
  validates :track_type, :inclusion => { :in => %w( bonus regular ) }

  belongs_to(
    :album,
    class_name: "Album",
    foreign_key: :album_id,
    primary_key: :id
  )

  has_many(
    :notes,
    :class_name => "Note",
    :foreign_key => :track_id,
    :primary_key => :id
  )
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible :email, :password

  validates :email, :password_digest, :session_token, :activation_token, :presence => true

  before_validation :ensure_session_token

  after_initialize :create_activation_token

  has_many(
    :notes,
    :class_name => "Note",
    :foreign_key => :user_id,
    :primary_key => :id
  )

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def self.generate_session_token
    SecureRandom.base64(16)
  end

  def create_activation_token
    self.activation_token = User.generate_session_token
  end

  def self.find_by_credentials(email, secret)
    user = User.find_by_email(email)
    return if user.nil?
    BCrypt::Password.new(user.password_digest).is_password?(secret) ? user : nil
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
  end

  def password=(secret)
    self.password_digest = BCrypt::Password.create(secret) unless secret.blank?
  end

  def is_password?(secret)
    self.password_digest.is_password?(secret)
  end

  def activated?
    self.activated
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController


  def index

  end

  def create
    album = Album.new(params[:album])

    if album.save
      redirect_to album_url(album)
    else
      render :json => album.errors.full_messages
    end
  end

  def new
    @album = Album.new
    render :new
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def update

  end

  def destroy
    Album.destroy(params[:id])

    render :text => "Album deleted"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index

  end

  def create
    band = Band.new(params[:band])

    if band.save
      redirect_to band_url(band)
    else
      render :json => band.errors.full_messages
    end
  end

  def new
    @band = Band.new
    render :new
  end

  def edit
    @band = Band.find(params[:id])
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def update

  end

  def destroy
    Band.destroy(params[:id])

    render :text => "Band deleted"
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def create
    note = Note.new(params[:note])

    if note.save
      redirect_to track_url(params[:note][:track_id])
    else
      render :json => note.errors.full_messages
    end

  end

  def destroy
    note = Note.find(params[:id])
    note_track = note.track_id

    Note.destroy(params[:id])

    redirect_to track_url(note_track)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if user.nil?
      render :text => "Credentials wrong"
    else

      sign_in(user)
      redirect_to user_url(user)
    end

  end

  def destroy
    sign_out_current_user
    redirect_to new_user_url
  end


end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def index

  end

  def create
    track = Track.new(params[:track])

    if track.save
      redirect_to track_url(track)
    else
      render :json => track.errors.full_messages
    end

  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def new
    @track = Track.new
    render :new
  end

  def show
    @track = Track.find(params[:id])
  end

  def update

  end

  def destroy
    Track.destroy(params[:id])

    render :text => "Track deleted"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    user = User.new(params[:user])

    if user.save
      UserMailer.activation_email(user).deliver!
      render :text => "Check your email for activation"
    else
      render :json => user.errors.full_messages
    end
  end

  def activate
    user = User.find(params[:id])
    user.activated = true
    user.save!

    sign_in(user)
    redirect_to user_path(user)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by_session_token(session[:token])
  end

  def logged_in?
    current_user
  end

  def log_in_user!
    current_user.reset_session_token!
    session[:token] = current_user.session_token
  end

  def sign_in(user)
    if user.activated?
      @current_user = user
      session[:token] = user.session_token
    else
      redirect_to new_sessions_url
    end
  end

  def sign_out_current_user
    current_user.reset_session_token!
    session[:token] = nil
  end


end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/albums/_form.html.erb
<% action_path = @album.persisted? ? band_album_path : band_albums_path %>

<form action='<%= action_path %>' method= "post">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <% if @album.persisted? %>
    <input type="hidden" name="_method" value= "put">
<% end %>

  <label for="album_band">Band</label>
  <select name=album[band_id] id="album_band">
    <% Band.all.each do |band| %>
      <option value="<%= band.id %>" <%= "selected" if (band.id == params[:band_id].to_i ) %> >
        <%= band.band_name %>
      </option>
    <% end %>
  </select>

  <label for="album_name">Album Name</label>
  <input  type="text" id="album_name" name="album[album_name]" value="<%=@album.album_name%>">

  <input type="radio" name="album[album_type]" id="album_version" value ="live" <%= "checked" if @album.album_type == "live" %> >
  <label for="album_version">Live</label><br>
  <input type="radio" name="album[album_type]" id="album_version" value ="studio" <%= "checked" if @album.album_type == "studio" %> >
  <label for="album_version">Studio</label>



  <input type="submit" value="Create Album!">

</form>

app/views/albums/edit.html.erb
<%= render "form" %>

app/views/albums/new.html.erb
<%= render "form" %>

app/views/albums/show.html.erb
<%= button_to "Delete Album", album_url, :method => :delete%>

<h2><%= @album.album_name %></h2>
<h3><%= link_to @album.band.band_name, band_url(@album.band) %></h3><p>

<table>
<% @album.tracks.each do |track| %>
<tr><td><%= link_to track.track_name, track_url(track) %></td></tr>
<% end %>
</table>

app/views/bands/_form.html.erb
<% action_path = @band.persisted? ? band_path : bands_path %>

<form action='/bands' method= 'post'>

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <% if @band.persisted? %>
    <input type="hidden" name="_method" value= "put">
  <% end %>


  <label for='band_name'>Band Name</label>
  <input  type="text" id='band_name' name='band[band_name]' value="<%= @band.band_name%>">

  <input type="submit" value="Create Band!">

</form>

app/views/bands/edit.html.erb
<%= render "form" %>

app/views/bands/index.html.erb
<% Band.all.each do |band| %>
<%= link_to band.band_name, band_url(band) %> <br>
<% end %>

app/views/bands/new.html.erb
<%= render "form" %>

app/views/bands/show.html.erb
<%= button_to "Delete Band", band_url, :method => :delete%>


<h2><%= @band.band_name %></h2>
<table>
  <% @band.albums.each do |album| %>

  <h3><th><%= link_to album.album_name, album_url(album) %></th></h3>
    <% album.tracks.each do |track| %>

    <tr><td><%= link_to track.track_name, track_url(track) %></td></tr>

    <% end %>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%#= stylesheet_link_tag    "application", :media => "all" %>
  <%#= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user.nil? %>
  <%= link_to "Log in", new_sessions_url %>
  <% else %>
  <%= current_user.email %>
  <%= button_to "Log out", sessions_url,   :method => "delete" %>
  <% end %>
  <p>

<%= yield %>

</body>
</html>

app/views/tracks/_form.html.erb
<% action_path = @track.persisted? ? album_track_path : album_tracks_path %>

<form action='<%= action_path %>' method= "post">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <% if @track.persisted? %>
    <input type="hidden" name="_method" value= "put">
  <% end %>

  <label for="track_album">Album</label>
  <select name=track[album_id] id="track_album">
    <% Album.all.each do |album| %>
      <option value="<%= album.id %>" <%= "selected" if (album.id == params[:album_id].to_i) %> >
        <%= album.album_name %>
      </option>
    <% end %>
  </select>
  <p>

  <label for="track_name">Track Name</label>
  <input  type="text" id="track_name" name="track[track_name]" value="<%= @track.track_name%>" >
  <p>

  <input type="radio" name="track[track_type]" id="track_type" value ="regular"
  <%= "checked" if @track.track_type == "regular" %> <%= "checked" if @track.track_type == "regular" %> >
  <label for="track_type">Regular</label>
  <input type="radio" name="track[track_type]" id="track_type" value ="bonus" <%= "checked" if @track.track_type == "bonus" %> >
  <label for="track_type">Bonus</label>
  <p>

  <label for="track_lyrics">Lyrics</label>
  <textarea id="track_lyrics" name="track[lyrics]" ><%= @track.lyrics%></textarea>
  <input type="submit" value="Create Track!">

</form>

app/views/tracks/_note.html.erb
<form action='<%=notes_url%>' method= "post">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <p>
  <label for="note_contents">Leave Note</label><br>
  <textarea id="note_contents" name="note[contents]" ></textarea>
  <name="key" value="value">
  <p>

  <input type="hidden" name="note[user_id]" value= "<%= current_user.id %>">
  <input type="hidden" name="note[track_id]" value= "<%= params[:id] %>">
  <input type="submit" value="Create Note">

</form>

app/views/tracks/edit.html.erb
<%= render "form" %>

app/views/tracks/new.html.erb
<%= render "form" %>

app/views/tracks/show.html.erb
<%= button_to "Delete Track", track_url, :method => :delete%>


<h2><%= @track.track_name %></h2>
<h3><%= link_to @track.album.album_name, album_url(@track.album) %></h3><p>
<h3><%= link_to @track.album.band.band_name, band_url(@track.album.band) %></h3><p>
  <% if logged_in? %>
    <%= render "note" %>
  <% end %>

<% @track.notes.each do |note| %>

  <%= note.author.email %>
  <%= note.contents %><br>
  <%= button_to "delete", note_url(note), :method => :delete %>
<% end %>

app/views/users/new.html.erb
<form action='/users' method= 'post' >
  <label for="user_email">Email</label>
  <input type="text" name="user[email]" id="user_email">
  <p>

  <label for="user_password">Password</label>
  <input type="text" name="user[password]" id="user_password">
  <p>

    <input type="submit" value="Create!">
</form>

app/views/users/show.html.erb
<%= current_user.email %>